# Generated by Django 4.2.2 on 2023-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_alter_vacancy_options_vacancy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название компании')),
                ('address_company', models.CharField(max_length=255, verbose_name='Адрес компании')),
                ('number_of_employees', models.IntegerField(blank=True, null=True, verbose_name='Число сотрудников')),
                ('is_hanting', models.BooleanField(default=True, verbose_name='Ищет сотрудников')),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Нет описания', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_relevant',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вакансия'),
        ),
    ]
